# Introduction to geographic chart in R

Zihao Liu

Our data in the real world often contains geographic location information, so it is inevitable to draw maps involving geographic coordinate systems. The geographic coordinate system uses a three-dimensional sphere to define the position of the earth's surface, so as to realize a coordinate system that references points on the earth's surface through latitude and longitude.

In this part, I will introduce some methods to draw geographic chart by using spatial data in R. Spatial data refers to data defined in a three-dimensional space with geographic location information. Map projection is a particularly important key technology when getting data. The most basic step of map information visualization is map projection, which converts the geographic coordinate information on the non-expandable surface to a two-dimensional plane, which is equivalent to surface parameterization. 

Since some data is in .shp or .shx which are data of projection of maps which can not be achieved by urls, I just wrote that in a pdf and uploaded it to my github alone with all the raw data for everyone to download.

The link of tutorial: 
https://github.com/Lzhntjs/edav_community_contribution/blob/master/Introduction%20to%20geographic%20chart%20in%20R.pdf


