# Meet the pets zoom session

Zhuoyue Hao

Overview
  
To help overcome the lack of personal interactions associated with remote learning, the project is designed to be hosting a zoom session on meeting the pets, which all pet lovers can participant no matter if they have pets or not.
At the beginning of the event, people who come with their pets will present a brief introduction about their pets, such as their names, breeds, ages, hobbies, favorite foods.

Then, people who come by themselves are expected to have some short videos (best if between 3-5 minutes) ready to share with everyone else. The videos could be any types – as long as it’s about pets! It should be really easy to find on YouTube or Tik-Tok.
  
We will also have some times for participants to exchange ideas on pet training techniques or feeding tips at the end of the session. People are welcomed to exchange contact information and stay in touch after the event, and hopefully we can have a chance to hang out in-person after the Covid period.

Milestones

- 2/8/2021: Introduced the idea of hosting a pet night during class discussion, and started a poll survey on Piazza
  o 12 out of 16 responders said that they were interested in the event, and 6 of them said that they will come with their pets
  
- 2/10/2021: Conducted a follow up google survey about participants’ preferable times and information of their pets

- 3/9/2021: Published the meeting details on Piazza and call for all pet lovers to participant

- 3/11/2021: The event took place at 8 p.m. EST, March 11th.
