# NBA data useful for a final project

Dipesh Patel

Sports is a common area for hobby data analysis and visualization. Here are some places to find publicly available data, for the NBA (National Basketball Association) in particular. Unique aspects of each data source are pointed out.

## stats.nba.com

i. data provided by the NBA itself.
ii. combine information on draft prospects available back to the 2014-15 season. can find under "events".
iii. lineup data available all the way back to 2007-08 season. can find under "teams".
iv. hustle stats available at both player and team level as far back as 2015-16.
v. player tracking data available from the 2013-14 season onward. however, data not available for all games which is something to note. under "players".
vi. clutch stats available back to the 1996-97 season. under "players".
vii. the "stats 101" tab is useful for any clarification on how terms are defined.
viii. filtering is available for most data and is easy to do.

## basketball-reference.com

i. most commonly used data website.
ii. all data can be converted easily to csv file format.
iii. positional estimate data available back to 1996-97 season. go to "season" then "player stats" then "play-by-play".
iv. league-adjusted shooting data available under "adjusted shooting".

## inpredictable.com

i. win probability data available back to the 1996-97 season. under "win probability added". measured at the player level. clarification on meaning of variables provided here: https://www.inpredictable.com/2014/01/nba-player-win-probability-added.html

## projects.fivethirtyeight.com/nba-player-ratings/

i. all-in-one metric, RAPTOR, available for each player and updated daily.
ii. more granular data available for download at the bottom of the page through the website's github. for example, distinctions are made between modern RAPTOR and historical RAPTOR as well as a forward looking predictive version of the metric called PREDATOR.
iii. construction of metrics is discussed here: https://fivethirtyeight.com/features/introducing-raptor-our-new-metric-for-the-modern-nba/

## pbpstats.com

i. team level data on after-event efficiency from the 2000-01 season can be found under "summary tables" then "pace/efficiency". An example of an event is the opponent misses a field goal attempt.

## kaggle.com/schmadam97/nba-playbyplay-data-20182019

i. contains game level play-by-play data scraped from basketball-reference.com starting from the 2015-16 season. separate dataset for each season.

## apanalytics.shinyapps.io/knarsu3/

i. various quantitative measures of player level defensive ability and downloadable in csv file format.
ii. uncertain terms explained clearly on home page.
iii. basic defensive versatility data to measure how many different position player guards.
iv. data on quality and role of opponent defended.

## other sites of potential interest that deal with "off-court" matters

i. spotrac.com for detailed contract information.
ii. basketball.realgm.com for transactions information.
iii. prosportstransactions.com/basketball/ for injury data.
  
** Note: idea for contribution drawn from 2020 Community Contributions Chapter 50 "Health datasets for the final project" by Natasha McLeod **
