on:
  push:
    branches:
      - main
      - master

name: bookdown

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EMAIL: ${{ secrets.EMAIL }}               # must be a verified email
      GH_TOKEN: ${{ secrets.GH_PAT }} # https://github.com/settings/tokens
 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@master

      - name: Cache bookdown results
        uses: actions/cache@v2
        with:
          path: _bookdown_files
          key: bookdown-${{ hashFiles('**/*Rmd') }}
          restore-keys: bookdown-

      - name: Install pak and query dependencies
        run: |
          install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/")
          saveRDS(pak::local_dev_deps_tree(), ".github/r-depends.rds")
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ matrix.config.os }}-${{ steps.install-r.outputs.installed-r-version }}-2-${{ hashFiles('.github/r-depends.rds') }}
          restore-keys: ${{ matrix.config.os }}-${{ steps.install-r.outputs.installed-r-version }}-2-
          
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install \
            libgdal-dev \
            libproj-dev \
            libmpfr6 \
            libmpfr-dev \
            libudunits2-dev	\
            default-jre \
            default-jdk 
          sudo R CMD javareconf  
      
      - name: Install dependencies	
        run: |	
          pak::local_install_dev_deps()	
        shell: Rscript {0}

      - name: Build site
        run: Rscript -e 'bookdown::render_book("index.Rmd", quiet = TRUE)'
      - uses: actions/upload-artifact@v2
        with:
          name: _book
          path: _book/
# and also add secrets for a GH_PAT and EMAIL to the repository
# gh-action from Cecilapp/GitHub-Pages-deploy
  checkout-and-deploy:
   runs-on: ubuntu-latest
   needs: build
   steps:
     - name: Checkout
       uses: actions/checkout@master
     - name: Download artifact
       uses: actions/download-artifact@v2
       with:
         # Artifact name
         name: _book # optional
         # Destination path
         path: _book/ # optional
         
          
     - name: Deploy to GitHub Pages
       uses: Cecilapp/GitHub-Pages-deploy@v3
       env:
         GITHUB_TOKEN: ${{ secrets.GH_PAT }}
       with:
         email: ${{ secrets.EMAIL }}  
         build_dir: _book/
         jekyll: no        # optional
